-- ==============================================================================
-- WeatherPulse India - PostGIS Migration 08: Active Early Warnings & Meteorological Alerts
-- Standards: IMD Four-Color Code Alert Protocol & WMO Disaster Early Warning Matrix
-- ==============================================================================

-- Clean up any expired or test records
DELETE FROM alerts WHERE id LIKE 'alt-in-%' OR id LIKE 'alt-sim-%';

INSERT INTO alerts (
    id, city_id, hazard, city, state, severity_color, severity_level, severity, type,
    start_time, end_time, expires_at, headline, description, message,
    safety_advice, forecast_value, threshold, source, source_type, is_active, created_at
) VALUES
-- 1. MUMBAI: RED ALERT (Extremely Heavy Rainfall & Coastal Flood Emergency)
(
    'alt-in-mumbai-01',
    'wp-city-mumbai',
    'HEAVY_RAINFALL',
    'Mumbai',
    'Maharashtra',
    'RED',
    'EXTREME_RED',
    'EXTREME_RED',
    'HEAVY_RAINFALL',
    CURRENT_TIMESTAMP - INTERVAL '1 hour',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    'Red Alert: Extremely Heavy Rainfall & Urban Flood Threat',
    'Offshore monsoon trough and low-pressure cyclonic shear zone bringing torrential precipitation across Mumbai Metropolitan Region and Konkan coastline.',
    'Extremely heavy precipitation with localized rainfall rates exceeding 218.4 mm/24h. Severe storm water drain inundation and high tide confluence expected at 02:45 PM (4.2m).',
    'Strictly avoid venturing into coastal zones and low-lying railway underpasses (Milan, Andheri, Hindmata subway). NDRF and SDRF teams on high alert. Fishermen prohibited from sea venture.',
    '218.4 mm / 24h (Observed & NWP)',
    'IMD Red Criteria: Rainfall > 204.5 mm/24h',
    'IMD Regional Meteorological Centre Mumbai & Doppler Radar (Veravali/Colaba)',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '1 hour'
),

-- 2. RAJASTHAN: RED ALERT (Severe Heatwave Emergency)
(
    'alt-in-jaipur-01',
    'wp-city-jaipur',
    'HEATWAVE',
    'Jaipur',
    'Rajasthan',
    'RED',
    'EXTREME_RED',
    'EXTREME_RED',
    'HEATWAVE',
    CURRENT_TIMESTAMP - INTERVAL '2 hours',
    CURRENT_TIMESTAMP + INTERVAL '72 hours',
    CURRENT_TIMESTAMP + INTERVAL '72 hours',
    'Red Alert: Severe Heatwave & High Thermal Stress Warning',
    'Persistent dry northwesterly winds and strong solar insolation creating intense heatwave conditions across Jaipur, Churu, Bikaner, and western districts.',
    'Maximum day temperatures forecasted to surge to 45.8°C with Heat Index reaching 51°C. High vulnerability for children, elderly, and outdoor labourers.',
    'Avoid direct sun exposure between 11:00 AM and 04:30 PM. Increase intake of oral rehydration fluids (ORS, lassi, lemon water). Keep livestock in shaded shelters with ample drinking water.',
    '45.8 °C (Departure: +5.4°C)',
    'IMD Red Criteria: Max Temp >= 45°C or Departure >= +6.4°C',
    'IMD Mausam National Weather Forecasting Centre (NWFC)',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '2 hours'
),

-- 3. ODISHA: RED ALERT (Cyclonic Squall & Coastal Storm Surge)
(
    'alt-in-bhubaneswar-01',
    'wp-city-bhubaneswar',
    'HIGH_WINDS_CYCLONE',
    'Bhubaneswar',
    'Odisha',
    'RED',
    'EXTREME_RED',
    'EXTREME_RED',
    'HIGH_WINDS_CYCLONE',
    CURRENT_TIMESTAMP - INTERVAL '30 minutes',
    CURRENT_TIMESTAMP + INTERVAL '60 hours',
    CURRENT_TIMESTAMP + INTERVAL '60 hours',
    'Red Alert: Deep Depression / Cyclonic Squall & High Sea Warning',
    'Well-marked low-pressure area over Northwest Bay of Bengal intensifying into a Deep Depression tracking toward northern Odisha and West Bengal coast.',
    'Sustained gale wind speeds of 75-85 km/h gusting to 95 km/h along Puri, Jagatsinghpur, Balasore, and Kendrapara coasts accompanied by tidal surge.',
    'Complete suspension of all offshore marine operations. Total ban on coastal fishing. Secure thatched roofs, unfastened solar panels, and construction cranes.',
    'Gale 85 km/h (Gusts: 95 km/h)',
    'IMD Red Criteria: Squall Wind >= 85 km/h + Storm Surge',
    'IMD Cyclone Warning Division (CWD New Delhi) & GDACS',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '30 minutes'
),

-- 4. DELHI NCR: ORANGE ALERT (Severe Convective Thunderstorm & Hail Squall)
(
    'alt-in-delhi-01',
    'wp-city-new-delhi',
    'THUNDERSTORM_LIGHTNING',
    'New Delhi',
    'Delhi',
    'ORANGE',
    'SEVERE_ORANGE',
    'ORANGE',
    'THUNDERSTORM_LIGHTNING',
    CURRENT_TIMESTAMP - INTERVAL '15 minutes',
    CURRENT_TIMESTAMP + INTERVAL '36 hours',
    CURRENT_TIMESTAMP + INTERVAL '36 hours',
    'Orange Warning: Severe Convective Thunderstorm & Hail Squall',
    'Western Disturbance interaction with moist easterly winds generating intense convective storm cells across Delhi NCR, Gurugram, Noida, and Faridabad.',
    'Intense thunderstorm activity accompanied by frequent cloud-to-ground lightning strikes, hail, and squally gusts of 55 to 65 km/h.',
    'Stay indoors; do not take shelter under solitary trees, electric transformers, or metal hoardings. Unplug electronic appliances and park vehicles away from old trees.',
    'Gusts: 62 km/h | CAPE: 2450 J/kg',
    'IMD Orange Criteria: Convective Gust >= 50 km/h + Severe Lightning',
    'IMD Radar Doppler Palam & Safdarjung Telemetry',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '15 minutes'
),

-- 5. ASSAM: ORANGE ALERT (Heavy Riverine Downpour & Brahmaputra Flood Alert)
(
    'alt-in-guwahati-01',
    'wp-city-guwahati',
    'HEAVY_RAINFALL',
    'Guwahati',
    'Assam',
    'ORANGE',
    'SEVERE_ORANGE',
    'ORANGE',
    'HEAVY_RAINFALL',
    CURRENT_TIMESTAMP - INTERVAL '3 hours',
    CURRENT_TIMESTAMP + INTERVAL '72 hours',
    CURRENT_TIMESTAMP + INTERVAL '72 hours',
    'Orange Warning: Heavy to Very Heavy Rainfall in Brahmaputra Basin',
    'Strong moisture-laden Southwesterly winds from Bay of Bengal hitting the Meghalaya plateau and Assam valley, causing intense orographic downpours.',
    'Widespread very heavy rainfall (115.6 to 164.2 mm) over Kamrup, Darrang, Barpeta, and Goalpara districts. Brahmaputra river approaching warning level.',
    'Residents in riverine char areas advised to monitor Central Water Commission (CWC) water level gauges and keep emergency disaster kits on standby.',
    '142.6 mm / 24h',
    'IMD Orange Criteria: Rainfall 115.6 - 204.4 mm/24h',
    'IMD Regional Meteorological Centre Guwahati & CWC Flood Forecast',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '3 hours'
),

-- 6. BENGALURU: ORANGE ALERT (Convective Cloudburst & Urban Drainage Watch)
(
    'alt-in-bengaluru-01',
    'wp-city-bengaluru',
    'HEAVY_RAINFALL',
    'Bengaluru',
    'Karnataka',
    'ORANGE',
    'SEVERE_ORANGE',
    'ORANGE',
    'HEAVY_RAINFALL',
    CURRENT_TIMESTAMP - INTERVAL '45 minutes',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    'Orange Warning: Severe Convective Downpour & Urban Inundation',
    'North-South wind discontinuity from South Interior Karnataka to Comorin area causing localized high-intensity evening convective showers.',
    'Rainfall intensity of 85-118 mm expected in 3 hours over East and South Bengaluru (Mahadevapura, Bellandur, Bommanahalli, Electronic City).',
    'Commuters advised to plan alternate routes and avoid underpasses. BBMP control room and disaster response squads deployed for desilt pumping.',
    '118.0 mm / 3h Cumulative',
    'IMD Orange Criteria: High Intensity Urban Downpour',
    'Karnataka State Natural Disaster Monitoring Centre (KSNDMC) & IMD Bengaluru',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '45 minutes'
),

-- 7. CHENNAI: ORANGE ALERT (High Swell Waves & Kallakkadal Marine Advisory)
(
    'alt-in-chennai-01',
    'wp-city-chennai',
    'HIGH_WINDS_CYCLONE',
    'Chennai',
    'Tamil Nadu',
    'ORANGE',
    'SEVERE_ORANGE',
    'ORANGE',
    'HIGH_WINDS_CYCLONE',
    CURRENT_TIMESTAMP - INTERVAL '4 hours',
    CURRENT_TIMESTAMP + INTERVAL '60 hours',
    CURRENT_TIMESTAMP + INTERVAL '60 hours',
    'Orange Warning: High Energy Swell Surge & Strong Coastal Winds',
    'Long-period swell waves originating from southern ocean swells reaching coastal Tamil Nadu and Andhra Pradesh coast.',
    'Sea surface waves reaching heights of 3.4 to 4.1 meters along Marina, Besant Nagar, and Ennore coastline with strong surface winds of 45-55 km/h.',
    'Fishermen and recreational beachgoers strictly cautioned against entering the surf zone. Small fishing boats must remain moored securely inside harbours.',
    'Wave Height: 3.8m | Wind: 52 km/h',
    'INCOIS High Wave Warning & IMD Marine Forecast',
    'Indian National Centre for Ocean Information Services (INCOIS)',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '4 hours'
),

-- 8. HIMACHAL PRADESH: ORANGE ALERT (Cloudburst & Landslide Warning)
(
    'alt-in-shimla-01',
    'wp-city-shimla',
    'FLASH_FLOOD',
    'Shimla',
    'Himachal Pradesh',
    'ORANGE',
    'SEVERE_ORANGE',
    'ORANGE',
    'FLASH_FLOOD',
    CURRENT_TIMESTAMP - INTERVAL '1 hour',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    'Orange Warning: Intense Mountain Rains & Landslide Vulnerability',
    'Active monsoon surge triggering heavy precipitation across Shimla, Solan, Mandi, and Kangra valleys with high runoff index.',
    'Rainfall amounts of 90-135 mm over 24 hours. High risk of mudslides, shooting stones on NH-5 (Chandigarh-Shimla) and Kullu highways.',
    'Avoid non-essential hill travel during nighttime. Maintain safe distance from overflowing mountain streams and nullahs.',
    '135.0 mm / 24h',
    'IMD Flash Flood Guidance Bulletin (FFG) & HPSDMA',
    'IMD Meteorological Centre Shimla & SDMA Himachal Pradesh',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '1 hour'
),

-- 9. KOLKATA: YELLOW ALERT (Thunderstorm with Lightning Watch)
(
    'alt-in-kolkata-01',
    'wp-city-kolkata',
    'THUNDERSTORM_LIGHTNING',
    'Kolkata',
    'West Bengal',
    'YELLOW',
    'MODERATE_YELLOW',
    'YELLOW',
    'THUNDERSTORM_LIGHTNING',
    CURRENT_TIMESTAMP - INTERVAL '2 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    'Yellow Advisory: Moderate Rain & Lightning Storm Watch',
    'Moist atmospheric instability causing passing convective cloud bands across Kolkata, Howrah, Hooghly, and North 24 Parganas.',
    'Moderate rain (35-55 mm) with surface wind gusts of 35-45 km/h and isolated lightning strikes during afternoon and evening.',
    'Keep umbrella handy; take safe shelter during active lightning flashes. Drive with low beams in sudden cloudbursts.',
    'Wind: 42 km/h | Rain: 48 mm',
    'IMD Yellow Criteria: Moderate Convective Activity',
    'IMD Regional Meteorological Centre Alipore Kolkata',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '2 hours'
),

-- 10. TELANGANA: YELLOW ALERT (Gusty Winds & Passing Showers)
(
    'alt-in-hyderabad-01',
    'wp-city-hyderabad',
    'HEAVY_RAINFALL',
    'Hyderabad',
    'Telangana',
    'YELLOW',
    'MODERATE_YELLOW',
    'YELLOW',
    'HEAVY_RAINFALL',
    CURRENT_TIMESTAMP - INTERVAL '1 hour',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    'Yellow Advisory: Light to Moderate Showers & Gusty Winds',
    'Low level westerly and northwesterly winds prevailing over Telangana bringing intermittent spells of moderate rain.',
    'Expect rainfall between 25-45 mm with gusty surface winds reaching 30-40 km/h in Hyderabad and Rangareddy district.',
    'Expect minor traffic slowing in low-elevation water pooling spots. GHMC monsoon teams on routine clearing duty.',
    '44.2 mm / 24h',
    'IMD Yellow Criteria: Rain 15.6 - 64.4 mm/24h',
    'IMD Meteorological Centre Hyderabad',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '1 hour'
),

-- 11. BIHAR: YELLOW ALERT (Dense Morning Fog / Low Visibility)
(
    'alt-in-patna-01',
    'wp-city-patna',
    'DENSE_FOG',
    'Patna',
    'Bihar',
    'YELLOW',
    'MODERATE_YELLOW',
    'YELLOW',
    'DENSE_FOG',
    CURRENT_TIMESTAMP - INTERVAL '4 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    'Yellow Advisory: Dense Fog & Sub-200m Visibility Watch',
    'High boundary layer moisture combined with light calm surface winds causing dense fog formation in early morning hours along Gangetic plains.',
    'Surface horizontal visibility expected to drop to 100-200 meters between 04:00 AM and 08:30 AM across Patna, Muzaffarpur, and Gaya.',
    'Highway drivers must use fog lamps and maintain ample following distances. Flight operations at Patna airport may experience minor delays.',
    'Visibility: 150 meters',
    'IMD Yellow Criteria: Visibility 50 - 200m',
    'IMD Meteorological Centre Patna',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '4 hours'
),

-- 12. GUJARAT: YELLOW ALERT (Warm Night & Moderate Heat Discomfort)
(
    'alt-in-ahmedabad-01',
    'wp-city-ahmedabad',
    'HEATWAVE',
    'Ahmedabad',
    'Gujarat',
    'YELLOW',
    'MODERATE_YELLOW',
    'YELLOW',
    'HEATWAVE',
    CURRENT_TIMESTAMP - INTERVAL '5 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    CURRENT_TIMESTAMP + INTERVAL '48 hours',
    'Yellow Advisory: Warm Night Conditions & High Heat Index',
    'Dry continental airmass sustaining elevated nocturnal temperatures with minimum temperatures remaining 4.5°C above seasonal normals.',
    'Nighttime minimum temperatures hovering near 29.8°C with elevated humidity index causing thermal discomfort.',
    'Ensure adequate cross-ventilation in living spaces. Drink sufficient water before going to bed.',
    'Min Temp: 29.8 °C (Departure: +4.6°C)',
    'IMD Yellow Criteria: Warm Night Departure >= +4.5°C',
    'IMD Meteorological Centre Ahmedabad',
    'official',
    TRUE,
    CURRENT_TIMESTAMP - INTERVAL '5 hours'
)
ON CONFLICT (id) DO UPDATE SET
    hazard = EXCLUDED.hazard,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    severity_color = EXCLUDED.severity_color,
    severity_level = EXCLUDED.severity_level,
    severity = EXCLUDED.severity,
    type = EXCLUDED.type,
    start_time = EXCLUDED.start_time,
    end_time = EXCLUDED.end_time,
    expires_at = EXCLUDED.expires_at,
    headline = EXCLUDED.headline,
    description = EXCLUDED.description,
    message = EXCLUDED.message,
    safety_advice = EXCLUDED.safety_advice,
    forecast_value = EXCLUDED.forecast_value,
    threshold = EXCLUDED.threshold,
    source = EXCLUDED.source,
    source_type = EXCLUDED.source_type,
    is_active = EXCLUDED.is_active;
